### ISSUE TITLE
Initial architecture

### ISSUE THREAD

**Issue by craicoverflow** [redhat-developer/app-services-sdk-go#1]
Before moving to the automation phase we should set up an initial project architecture following best practices.

## Proposed layout

The kubernetes Go client has a good layout which we can adopt. See [this example](https://github.com/kubernetes/client-go/tree/master/pkg/apis/clientauthentication/v1beta1).

Example layout:

```shell
├── apis
│   ├── accountmgmt
│   │   └── v1
│   │       └── go.mod
│   ├── kafka
│   │   ├── admin
│   │   │   └── v1beta1
│   │   │       └── go.mod
│   │   └── fleetmanager
│   │       └── v1beta1
│   │           └── go.mod
│   └── serviceregistry
│       └── v1alpha1
│           └── go.mod
├── auth
├── config
├── go.mod
├── logging
```

Sub-modules can be used to allow users to import specific packages without having to import the entire SDK into their project:

```go
import (
   "github.com/redhat-developer/apis/kafka/admin/v1beta1"
   "github.com/redhat-developer/apis/kafka/fleetmanager/v1beta1"
)
```

**Comment by wtrocki** [comment]
Quick question - is SDK responsibility to maintain API versioning? Should OpenAPI keep all future versions (having multiple versions in OpenAPI is very common). Happy to chat about it but seems like we can simply overwrite content every time we get new API (And track versioning in releases/tags.

**Comment by craicoverflow** [comment]
> Quick question - is SDK responsibility to maintain API versioning?

We need to chat about this to ensure we are on the same page, but yes SDK will also maintain the API version(s) as long as they are still active.
