### ISSUE TITLE
Mixture of upstream/product folder names in the SDK

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-sdk-go#121]
kafkamgmt - uses common world
srsmgmt - uses srs which is internal name, same as kas.

```
kafka vs kas
srs vs serviceregistry vs registry
```

It will strongly suggest renaming package to registrymgmt before we get more usage.

**Comment by craicoverflow** [comment]
Yeah you are right.

**Comment by wtrocki** [comment]
Done in #130
