### ISSUE TITLE
Provide (copy) documentation for authentication and other useful elements that are cross cutting concerns.

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-sdk-go#123]
See SDK-js for example on how this can be done.

**Comment by craicoverflow** [comment]
I wouldn't consider this a blocker, but we should have it.

**Comment by wtrocki** [comment]
Removed! Thx

**Comment by wtrocki** [comment]
SDK's are not aligned. I been talking with team that were confused about go vs js-sdk. I think we should copy those docs ASAP.
https://github.com/redhat-developer/app-services-sdk-js/blob/main/docs/authentication.md#authentication-for-instance-sdks
