### ISSUE TITLE
Add examples that can be used when building to actually verify if there are breaking changes 

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-sdk-go#124]
Examples will be used for testing SDK etc.

**Comment by wtrocki** [comment]
@craicoverflow Java and JS have those in very minimal level - Just doing list on resource

**Comment by wtrocki** [comment]
Done by @craicoverflow

**Comment by craicoverflow** [comment]
If you think about it, these examples will give us a false sense of whether there are breaking changes, as the examples only test one or two methods out of potentially hundreds.

**Comment by wtrocki** [comment]
Yes.. That is minimum we have. There is separate issue for testing all API:
https://github.com/redhat-developer/app-services-sdk-go/issues/128
