### ISSUE TITLE
All apis should be regenerated all the time and removing previous files

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-sdk-go#125]
I have noticed that service registry have files that are not present on the openapi.
In other SDK's we remove generated code before generation. 
Go might need that as well.

Phantom models (like BlahAPI.go) will cause major problems in the future.

**Comment by craicoverflow** [comment]
Agreed.

**Comment by wtrocki** [comment]
We need to cleanup folder before we generate new APIs
