### ISSUE TITLE
Generation is overriding current PR's 

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-sdk-go#126]
When 2 changes in the generation will happen my commits were lost as automation forcepushes changes to the same branch.
Additionally branch name should include id of the API.

Solution will be to have suffix added to branch with apiID and some timestamp?
Without that we are likely to loose changes. 

TL;DR - `chore/add-openapi` gets overwritten every time changes happen - We have lost update of one api that were overridden by other.

**Comment by craicoverflow** [comment]
> Solution will be to have suffix added to branch with apiID and some timestamp?

yeah, I had tried to include the API ID for this and it did not work for me.

With the create-pull-request action you can do:

```yaml
with:
  branch-suffix: timestamp
```

To generate a unique branch.

**Comment by wtrocki** [comment]
>  you can do:

That will solve problem IMHO, but not confident enough to do it myself right now.

**Comment by craicoverflow** [comment]
Let's see is #134 fixed this.
