### ISSUE TITLE
SDK UX issues and problems with packages

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-sdk-go#129]
My further recommendation for **all** apis will be to:

- Drop `apiv1` etc. We do not actually have the means to keep API's versions like Kubernetes does and it is confusing for people
- Use the same package name as a folder - currently we are importing `apiv1` but the package name is different which is confusing

Double imports (generated code and wrapper can be fixed by having both in the same package. 
We will only need to add ignorefile for the generator in that instance.

Related issues:
#125

**Comment by craicoverflow** [comment]
> - Drop `apiv1` etc. We do not actually have the means to keep API's versions like Kubernetes does and it is confusing for people

In what way do you mean we do not have the means? As in we will not maintain multiple concurrent API versions? We would! What do you suggest we do once `apiv2` is introduced?

> Use the same package name as a folder - currently we are importing apiv1 but the package name is different which is confusing

It is not. It is quite common:

https://github.com/googleapis/google-cloud-go/blob/master/servicemanagement/apiv1/service_manager_client.go#L17

> We will only need to add ignorefile for the generator in that instance.

What would we ignore?

**Comment by wtrocki** [comment]
> What do you suggest we do once apiv2 is introduced?

Every breaking change will need new version and previous versions will simply stop working.

> What would we ignore?

Our own written code/wrapper in the same package

**Comment by wtrocki** [comment]
Google SDK maps more kubernetes but our backend doesnt work this way. In kube you would have openapi per version and no breaking changes in version.

Sadly this not reflecting how our services work

**Comment by craicoverflow** [comment]
> Every breaking change will need new version and previous versions will simply stop working.

That is not necessarily true - you can have different customers on different major versions! You can't expect a customer to be able to immediately upgrade their version - they may have a grace/deprecation period of a year to move over. In the meantime you would have new customers who go straight to v2.

> Our own written code/wrapper in the same package

I still don't understand. Why would we ignore our custom wrapper? Can you be more explicit to help me understand.

> Google SDK maps more kubernetes but our backend doesnt work this way. In kube you would have openapi per version and no breaking changes in version.

Hmm. This has little to do with k8s API versioning. This is mapping to semantic versioning.

**Comment by wtrocki** [comment]
> That is not necessarily true - you can have different customers on different major versions

Hi

I think this ending up as some heated discussion. 
Lets close this issue - want to avoid discussions with exclamation marks 

We both have good understanding of problem but talking about different things.
What kubernetes does is openapi snapshotting with each version being immutable,  our backend uses single openapi file with versioning that is allowed to change.

What our backend folks will do is to have new endpointns with duplication (v2 or something) in the same openapi. 

As outsider/sdk user I was amazed that we adapted snapshotting but then I got breaking change on the same version and decided to create this issue.

**Comment by craicoverflow** [comment]
Thank you for the background context as to the reasoning for this - it helps make things more clear.

> but then I got breaking change on the same version and decided to create this issue

Was there a v2 bump in one of the APIs?

**Comment by wtrocki** [comment]
> Was there a v2 bump in one of the APIs?

You mean openapi file version?

**Comment by craicoverflow** [comment]
> > Was there a v2 bump in one of the APIs?
> 
> You mean openapi file version?

Yes kind of. I mean was there a bump to one of the API paths in one of the OpenAPI files?

**Comment by wtrocki** [comment]
No. No bump on version. Ideally linter will fix that problem in long run with rule:

- If there was the change version of the file should be changed.

**Comment by craicoverflow** [comment]
> No for both actually. No bump on version. 

yeah so even though these APIs are using `v1` they are more realistically in `v1beta`:

https://github.com/redhat-developer/app-services-sdk-go#supported-apis

Ideally APIs deployed should be `/api/v1beta` when still in beta but they were already deployed like this.
