### ISSUE TITLE
SDK build on PR should happen over the generated code 

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-sdk-go#153]
SDK build on PR should happen over the generated code rather than current codebase. 
This way we can actually check if PR is even valid and compiles. 

I have applied this flow in https://github.com/redhat-developer/app-services-sdk-js/pull/77

**Comment by wtrocki** [comment]
CC @craicoverflow - idea here is that when openapi file lands it actually builds wrong code - it builds main branch code rather than code that will be result of the OpenAPI change. This is trivial fix - requires reordering of the build workflow

**Comment by craicoverflow** [comment]
Ack. Will do this.

**Comment by craicoverflow** [comment]
Actually, little bit unsure what to do - could you give me a pointer or maybe do this one since you have done it in the other repos?

**Comment by wtrocki** [comment]
Actually I'm also missing some context:

https://github.com/redhat-developer/app-services-sdk-go/blob/main/.github/workflows/build_and_validate.yaml

This workflow should:

1. Generate new source code
2. Execute `go build`

While second step is trivial. I will need some help with generation of source code as other SDK's do it differently.

**Comment by wtrocki** [comment]
I will reply issue description with more visual description:

So we get PR with simple openapi change.
Build passes but we still do not know:

 - if generation will work (it can fail)
 - If generated code will be valid (this wasn't true many times)

We merge and automation PR will fail to create or will produce invalid content.
We should know that before merging openapi change.

**Comment by craicoverflow** [comment]
I understand now. thanks, i can do that.
