### ISSUE TITLE
Introduce go submodules to use independent versioning 

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-sdk-go#160]
For projects that use multiple SDK sometimes we need to update one and stay with old version of the other. 

Imagine scenario:
v0.5.0 
- kafka-mgmt 
- registry-mgmt

Now we want received 2 changes for those apis independently but only want to use registry change. 
Users should be able to import SDK's individually with different versions

- kafka-mgmt 0.5.1
- registry-mgmt 0.5.0

**Comment by wtrocki** [comment]
I think CLI should use individual imports rather than entire SDK

**Comment by craicoverflow** [comment]
I am going to pick up this now. This has caused many headaches already so it would be good to have it done soon.

**Comment by craicoverflow** [comment]
> Releases should be the same

I don't know whether I agree with this. What would be the main reasoning for this? You could end up in a situation where a less active API has had 0 changes between dozens of releases. This would also mean we could be creating minor releases with no new features added, which goes against SemVer and would also lead to some confusion by consumers.

**Comment by wtrocki** [comment]
> I don't know whether I agree with this

You are right. This comment was old and outdated.
