### ISSUE TITLE
./scripts folder contains unused scripts 

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-sdk-go#205]
fetch_api and generate, generate_all etc. are no longer used causing confusion on how to generate codebase. 
Scripts arent working anymore.

**Comment by wtrocki** [comment]
Would remove those but not sure if there are any plans to keep them, or reuse some of content. 

CC @craicoverflow

**Comment by craicoverflow** [comment]
They can be removed. They were probably kept in longer as a fallback, but have now fallen out of date.
