### ISSUE TITLE
KAS Fleet Manager doesn't meet validator rules

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-sdk-go#217]
https://github.com/redhat-developer/app-services-sdk-go/runs/3251943870?check_suite_focus=true

CC @craicoverflow what is the process for this?

**Comment by craicoverflow** [comment]
Reach out to the team for a fix.

In the mean time I have created an issue to add a rule for this: https://github.com/redhat-developer/app-services-api-guidelines/issues/8

**Comment by craicoverflow** [comment]
Done.
