### ISSUE TITLE
Add ability to release all SDKs at once

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-sdk-go#260]
We need ability to release all SDK at once by automation.

**Comment by craicoverflow** [comment]
> Creating tag on the root should create individual releases for other SDKs

No, it should not. The root module is completely independent from the submodules. 

Why does it need this?

**Comment by wtrocki** [comment]
Understood. Will do it without creating tag for the whole repo (making repo wide release of all components)

**Comment by craicoverflow** [comment]
Since you have assigned this to yourself, can you update the description and title to reflect what will be done?

**Comment by wtrocki** [comment]
Done
