### ISSUE TITLE
Define a single `APIConfig` type in the root module and reference it from individual SDKs.

### ISSUE THREAD

**Issue by craicoverflow** [redhat-developer/app-services-sdk-go#261]
Each submodule has the same API Config properties. It would make more sense to define a single type in the root module (in `internal`) and reference that type in a new type in each SDK.

**Comment by alexal** [comment]
@craicoverflow I would like to work on this.

**Comment by craicoverflow** [comment]
Sure thing! I will assign you. We actually had this in the past, before moving to submodules, so it would be something similar again :)

https://github.com/redhat-developer/app-services-sdk-go/blob/v0.9.0/kafkamgmt/apiv1/api_client.go#L11
