### ISSUE TITLE
Move config package from CLI

### ISSUE THREAD

**Issue by craicoverflow** [redhat-developer/app-services-sdk-go#45]
This is actually very important to have in the SDK repo as authorization and authentication heavily rely on it and need to persist the access token somewhere.

```go
kafkaMgmtAPI := kafkamgmt.NewClientFromConfig()
```

Without it, the SDK is useless to other tools such as the upstream Terraform Provider.

**Comment by craicoverflow** [comment]
@wtrocki I would say that the JS repo will require a config abstraction also?

**Comment by wtrocki** [comment]
@craicoverflow It depends. I would create duplicate to investigate config abstraction based on the kas-UI.
However Login on Kas-UI is little bit convoluted because of insights. Would create investigation for this in js-sdk

**Comment by craicoverflow** [comment]
I think we need a couple of ways to create a config client - with and without using the `~/config/rhoas/config.json` as source for the tokens.

**Comment by craicoverflow** [comment]
Actually having done some checks, do we want to have the SDK tightly coupled to the config like this?

It is not something I have seen as a common pattern, the main exception being Kubernetes but that is much more complex.

@pmuir I know you were using it in the Terraform Provider, but this was only using a small portion of fields for making API requests (after authentication). 

```go
accessToken, _ := authsdk.Authenticate(offlineToken, clientID) // hypothetical way to get access token for your Go application.

kafkaAPI := kafkamgmt.NewAPIClient(...)
```

It will also mean we need to protect against concurrency as we have multiple applications using the config - and if the CLI is logged in using the browser-based flow the config will be incompatible as the client ID will not work for the offline token and vice-versa.

At this point I don't think we need config persistence in the SDK.

**Comment by pmuir** [comment]
I think leave it out for now - I only was using it because it was tightly wound into the API.
