### ISSUE TITLE
Define unique identifier for each API client

### ISSUE THREAD

**Issue by craicoverflow** [redhat-developer/app-services-sdk-go#50]
Currently the metadata config uses the name of the OpenAPI spec file as the key - but this is not always unique.

```json
{
  "kas-fleet-manager.yaml": {
    "apiGroup": "kafkamgmt",
    "apiVersion": "v1",
    "release_level": "beta"
  },
  "srs-fleet-manager.json": {
    "apiGroup": "serviceregistrymgmt",
    "apiVersion": "v1",
    "release_level": "alpha"
  },
  "rest": 😞 
}
```

We need to define a unique identifier format for this, something like:

`{{ github.repo }}/{{service-name}}`

```json
{
  "github.com/bf2/kafka-mgmt": {
    "apiGroup": "kafkamgmt",
    "apiVersion": "v1",
    "release_level": "beta"
  },
  "github.com/bf2/serviceregistry-mgmt": {
    "apiGroup": "serviceregistrymgmt",
    "apiVersion": "v1",
    "release_level": "alpha"
  },
  "github.com/bf2/kafka-admin": 😄 
}
```

cc @wtrocki @secondsun

**Comment by wtrocki** [comment]
Those needs to be unique acoross different SDK (probably). Github and bf2 seems redundant (bf2 will be renamed to something else in coming weeks.

`kafka-mgmt` would be ok as we will control keys and keep them unique anyway. It is not like we will get new service every week.

**Comment by craicoverflow** [comment]
Okay so a new proposed payload format which the API would send:

```json
{
   "id":"kafka-mgmt",
   "source":"./openapi/kas-fleet-manager.yaml"
}
```


```json
{
   "id":"kafka-admin",
   "source":"./path/to/source/rest.yaml"
}
```

**Comment by craicoverflow** [comment]
Updated the ID with the API version.

**Comment by wtrocki** [comment]
Amazing!
