### ISSUE TITLE
Investigate if we can override or customise the generated API client READMEs

### ISSUE THREAD

**Issue by craicoverflow** [redhat-developer/app-services-sdk-go#54]
The generated README for each API client is very unclear and convoluted - it is aimed at an API client which is generated inside your own code - not as an externally consumed package.

[Documentation for API Endpoints](https://github.com/redhat-developer/app-services-sdk-go/blob/main/kafkamgmt/apiv1/README.md#documentation-for-api-endpoints) onwards is useful so this is not just a case of not generating the README and writing our own.

OpenAPI Generator has [customization options](https://openapi-generator.tech/docs/customization) through templates so this is a possible approach we should investigate further.

**Comment by wtrocki** [comment]
Sounds like we need custom templates with ascidocs.
