### ISSUE TITLE
Integrate Kafka Admin API

### ISSUE THREAD

**Issue by craicoverflow** [redhat-developer/app-services-sdk-go#6]
Needs to be done after the **Expose Kafka instance API to end users** epic

**Comment by craicoverflow** [comment]
The Kafka Admin API now use GitHub Actions to create their releases so we could hook into that lifecycle eventually:

https://github.com/bf2fc6cc711aee1a0c2a/kafka-admin-api/blob/main/.github/workflows/release.yml

**Comment by wtrocki** [comment]
Let's disscus options with team wider team around dataplane approach:

We have two options:

1) Generate SDK for dataplanes and also make them available upstream for upstream CLI to use if needed
2) Invest more time into plugin architecture: Kafka/SRS CLIS technically could be reusable

Benefits of 1 is that we can technically help UI and CLI.
Benefits of 2 are more cleaner CLI plugin story and making CLI dataplane more or less plugin based (will mean that teams could create them upstream and we can merge them.

**Comment by wtrocki** [comment]
My take is that 1 is must and two can be added later. SDK's are needed for UI and CLI anyway:

https://github.com/bf2fc6cc711aee1a0c2a/kafka-ui/blob/main/openapi/kafka-admin.yaml
