### ISSUE TITLE
Integrate Service Registry API

### ISSUE THREAD

**Issue by craicoverflow** [redhat-developer/app-services-sdk-go#7]

**Comment by wtrocki** [comment]
I would recomend to split this task between - integration with schema push and actual generation. 
We know that schema push will work (and for the moment we are not interested in their original schema (as big changes are made). It could be good to simply assume that file was placed in location and generate it. 

Recomended file:
https://github.com/redhat-developer/app-services-cli/blob/f7021bfc5a3a5af461dc91b9181cabee227c7bf4/openapi/srs-fleet-manager.json
