### ISSUE TITLE
Use a custom template to create an API client

### ISSUE THREAD

**Issue by craicoverflow** [redhat-developer/app-services-sdk-go#76]
Currently the SDK has a custom wrapper and README to give us control over some of the generated APIs we do not like. It makes more sense to use a custom template for this.

These can be added here: https://github.com/redhat-developer/app-services-sdk-go/tree/main/scripts/templates

This would also resolve #54

**Comment by wtrocki** [comment]
Amazing idea! Readme seems to be good example of override as it carries low risk and we can always fall back to original in case of breaking changes. The same doesn't translate to code.

**Comment by craicoverflow** [comment]
Yeah, the README for sure would be something worth investing in templating.

**Comment by wtrocki** [comment]
Is this generated:
https://github.com/redhat-developer/app-services-sdk-go/blob/main/srsmgmt/apiv1/README.md

**Comment by craicoverflow** [comment]
No.
