### ISSUE TITLE
Use a tool like openapi-diff to generate an informative changelog

### ISSUE THREAD

**Issue by craicoverflow** [redhat-developer/app-services-sdk-go#98]
https://www.npmjs.com/package/openapi-diff groups changes into:

- Breaking changes
- Non Breaking Differences
- Other

This could be used to generate a clear diff of what has changed between releases and could be added to the release notes.

**Comment by wtrocki** [comment]
Similar issue https://github.com/redhat-developer/app-services-sdk-go/issues/127
