### ISSUE TITLE
Add accountmgmt service

### ISSUE THREAD

**Issue by craicoverflow** [redhat-developer/app-services-sdk-go#99]
This would need to be pulled rather than pushed - maybe with a daily cron job or something?

cc @wtrocki the JS-SDK may need this also.

**Comment by wtrocki** [comment]
Oh.. yes. This OpenAPI is huge and I would need to investigate if we want to this entire thing or cloud.redhat.com specific elements. Let's drop that on today's refinement discussion. Good topic!

**Comment by craicoverflow** [comment]
Yeah, we may be able to filter just the _one_ endpoint we need.

**Comment by craicoverflow** [comment]
After discussion with the team, we do not want to do this. It will eventually becoming part of another SDK.

**Comment by wtrocki** [comment]
My take is that if that is single enpoint we do not need to generate anything. Just copy what we need and maintain it as some library in CLI maybe?
